-- MySQL Script generated by MySQL Workbench
-- Seg 26 Out 2015 19:14:20 BRST
-- Model: database    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scientific_venus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `scientific_venus` ;

-- -----------------------------------------------------
-- Schema scientific_venus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scientific_venus` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `scientific_venus` ;

-- -----------------------------------------------------
-- Table `scientific_venus`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`paciente` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`paciente` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `nascimento` DATE NOT NULL,
  `religiao` VARCHAR(45) NOT NULL,
  `religiaoNote` VARCHAR(45) NULL,
  `etnia` VARCHAR(45) NOT NULL,
  `etniaNote` VARCHAR(45) NULL,
  `escolaridade` VARCHAR(45) NOT NULL,
  `escolaridadeNote` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `estadoCivilNote` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`prontuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`prontuario` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`prontuario` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `paciente_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `registro` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `paciente_id_idx` (`paciente_id` ASC),
  CONSTRAINT `paciente_id`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `scientific_venus`.`paciente` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`consulta` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`consulta` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `prontuario_id` INT NOT NULL,
  `pesquisador` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_consulta_1_idx` (`prontuario_id` ASC),
  CONSTRAINT `fk_consulta_1`
    FOREIGN KEY (`prontuario_id`)
    REFERENCES `scientific_venus`.`prontuario` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`exameFisico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`exameFisico` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`exameFisico` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `peso` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  `imc` VARCHAR(45) NULL,
  `pressaoArterial` VARCHAR(45) NULL,
  `circunferenciaAbdominal` VARCHAR(45) NULL,
  `circunferenciaCervical` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_exameFisico_1_idx` (`consulta_id` ASC),
  CONSTRAINT `fk_exameFisico_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `scientific_venus`.`consulta` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`antecedentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`antecedentes` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`antecedentes` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `situacaoAborto` TINYINT(1) NULL,
  `situacaoGestacao` TINYINT(1) NULL,
  `situacaoParidade` TINYINT(1) NULL,
  `tabagismo` TINYINT(1) NULL,
  `hac` TINYINT(1) NULL,
  `hacType` VARCHAR(45) NULL,
  `diabetes` TINYINT(1) NULL,
  `diabetesType` VARCHAR(45) NULL,
  `hipotireoidismo` TINYINT(1) NULL,
  `hipotireoidismoType` VARCHAR(45) NULL,
  `note` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_antecedentes_1_idx` (`consulta_id` ASC),
  CONSTRAINT `fk_antecedentes_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `scientific_venus`.`consulta` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`ultrassom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`ultrassom` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`ultrassom` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `volumeUterino` VARCHAR(45) NULL,
  `ovarioDireito` VARCHAR(45) NULL,
  `ovarioEsquerdo` VARCHAR(45) NULL,
  `endometro` VARCHAR(45) NULL,
  `nd` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_ultrassom_1_idx` (`consulta_id` ASC),
  CONSTRAINT `fk_ultrassom_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `scientific_venus`.`consulta` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`escalas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`escalas` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`escalas` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `pbacInicial` VARCHAR(45) NULL,
  `beckInicial` VARCHAR(45) NULL,
  `vidaMioma` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_escalas_1_idx` (`consulta_id` ASC),
  CONSTRAINT `fk_escalas_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `scientific_venus`.`consulta` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`exames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`exames` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`exames` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `hb` VARCHAR(45) NULL,
  `ht` VARCHAR(45) NULL,
  `vcm` VARCHAR(45) NULL,
  `rdw` VARCHAR(45) NULL,
  `ferro` VARCHAR(45) NULL,
  `ferritina` VARCHAR(45) NULL,
  `vitaminaD3` VARCHAR(45) NULL,
  `gj` VARCHAR(45) NULL,
  `ct` VARCHAR(45) NULL,
  `ldl` VARCHAR(45) NULL,
  `hdl` VARCHAR(45) NULL,
  `tsh` VARCHAR(45) NULL,
  `t4l` VARCHAR(45) NULL,
  `tgl` VARCHAR(45) NULL,
  `colo` VARCHAR(45) NULL,
  `lombar` FLOAT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_exames_1_idx` (`consulta_id` ASC),
  CONSTRAINT `fk_exames_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `scientific_venus`.`consulta` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`conduta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`conduta` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`conduta` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `conduta` VARCHAR(45) NULL,
  `cirurgia` VARCHAR(45) NULL,
  `hormonioTerapia` VARCHAR(45) NULL,
  `hormonioTerapiaAINH` VARCHAR(45) NULL,
  `hormonioTerapiaCiclico` TINYINT(1) NULL,
  `hormonioTerapiaContinuo` TINYINT(1) NULL,
  `hormonioTerapiaNome` VARCHAR(45) NULL,
  `ainh` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_conduta_1_idx` (`consulta_id` ASC),
  CONSTRAINT `fk_conduta_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `scientific_venus`.`consulta` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`resultados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`resultados` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`resultados` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `pbacFinal` VARCHAR(45) NULL,
  `beckFinal` VARCHAR(45) NULL,
  `vidaMioma` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_resultados_1_idx` (`consulta_id` ASC),
  CONSTRAINT `fk_resultados_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `scientific_venus`.`consulta` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`mioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`mioma` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`mioma` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `medida` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_mioma_1_idx` (`consulta_id` ASC),
  CONSTRAINT `fk_mioma_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `scientific_venus`.`consulta` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scientific_venus`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scientific_venus`.`log` ;

CREATE TABLE IF NOT EXISTS `scientific_venus`.`log` (
  `_id` INT NULL AUTO_INCREMENT,
  `agent` VARCHAR(180) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `timezone` INT NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
